/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author verap
 */
public class TelaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form TelaPrincipal
     */
    public int v1, v2, v3, v4, v5;
    private double saldo;
    
    public TelaPrincipal() {
        initComponents();   
        
        jTxtDepositar.setDocument(new SoNumeros());
        jTextValor1.setDocument(new SoNumeros());
        jTextValor2.setDocument(new SoNumeros());
        jTextValor3.setDocument(new SoNumeros());
        jTextValor4.setDocument(new SoNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtDepositar = new javax.swing.JTextField();
        jTextName1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextValor1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPagar1 = new javax.swing.JButton();
        status1 = new java.awt.Checkbox();
        jTextName2 = new javax.swing.JTextField();
        jTextValor2 = new javax.swing.JTextField();
        jPagar2 = new javax.swing.JButton();
        status2 = new java.awt.Checkbox();
        jTextName3 = new javax.swing.JTextField();
        jTextValor3 = new javax.swing.JTextField();
        jPagar3 = new javax.swing.JButton();
        status3 = new java.awt.Checkbox();
        jTextName4 = new javax.swing.JTextField();
        jTextValor4 = new javax.swing.JTextField();
        jPagar4 = new javax.swing.JButton();
        status4 = new java.awt.Checkbox();
        jTextName5 = new javax.swing.JTextField();
        jTextValor5 = new javax.swing.JTextField();
        status5 = new java.awt.Checkbox();
        jLabel3 = new javax.swing.JLabel();
        jTxtSaldo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPagarAll = new javax.swing.JButton();
        jPagarAllSincronizado = new javax.swing.JButton();
        jConcluir = new javax.swing.JButton();
        jPagar5 = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Depositar R$");

        jLabel2.setText("Nome");

        jTxtDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDepositarActionPerformed(evt);
            }
        });

        jTextName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextName1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Valor a pagar");

        jTextValor1.setToolTipText("");
        jTextValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValor1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Status");

        jPagar1.setText("Pagar");
        jPagar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPagar1ActionPerformed(evt);
            }
        });

        jTextName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextName2ActionPerformed(evt);
            }
        });

        jTextValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValor2ActionPerformed(evt);
            }
        });

        jPagar2.setText("Pagar");
        jPagar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPagar2ActionPerformed(evt);
            }
        });

        jTextName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextName3ActionPerformed(evt);
            }
        });

        jTextValor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValor3ActionPerformed(evt);
            }
        });

        jPagar3.setText("Pagar");
        jPagar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPagar3ActionPerformed(evt);
            }
        });

        jTextName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextName4ActionPerformed(evt);
            }
        });

        jTextValor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValor4ActionPerformed(evt);
            }
        });

        jPagar4.setText("Pagar");
        jPagar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPagar4ActionPerformed(evt);
            }
        });

        jTextName5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextName5ActionPerformed(evt);
            }
        });

        jTextValor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValor5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Saldo R$");

        jTxtSaldo.setEditable(false);
        jTxtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSaldoActionPerformed(evt);
            }
        });

        jLabel6.setText("Usuários do cartão");

        jPagarAll.setText("Pagamento ao mesmo tempo");
        jPagarAll.setActionCommand("");
        jPagarAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPagarAllActionPerformed(evt);
            }
        });

        jPagarAllSincronizado.setText("Pagamento ao mesmo tempo sincronizado");
        jPagarAllSincronizado.setActionCommand("");
        jPagarAllSincronizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPagarAllSincronizadoActionPerformed(evt);
            }
        });

        jConcluir.setText("Concluir");
        jConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConcluirActionPerformed(evt);
            }
        });

        jPagar5.setText("Pagar");
        jPagar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPagar5ActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel7.setText("R$");

        jLabel8.setText("R$");

        jLabel9.setText("R$");

        jLabel10.setText("R$");

        jLabel11.setText("R$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextName4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextName2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextName3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextName1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextName5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPagar1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPagar2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextValor4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPagar4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextValor3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPagar3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextValor5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPagar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(status2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(status3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(status4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(status5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPagarAllSincronizado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPagarAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jConcluir)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jTxtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConcluir)
                    .addComponent(jTxtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPagar1)
                        .addComponent(jLabel7))
                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(status4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextValor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPagar4)
                                .addComponent(jLabel10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPagar2)
                            .addComponent(jTextValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPagar3)
                            .addComponent(jTextValor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextName5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPagar5)
                        .addComponent(jTextValor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPagarAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPagarAllSincronizado)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
     public void sacar(int valor, String cliente){
        
    	if(saldo >= valor){                
    		double saldoOriginal = saldo;
                
    		System.out.println(cliente + " vai sacar" );
    		//tempo para aguardar saque
    		try{
    			System.out.println(cliente + " esperando" );
    			Thread.sleep(1000); // aguarda processamento de 1 seg
    		} catch (InterruptedException e){}
    		
    		saldo -= valor;
    		String msg = cliente + " SACOU " + valor 
    			+ " [Saldo Original= " + saldoOriginal 
    			+ " Saldo Final= " + saldo + "]";
    		System.out.println(msg);
    	}else{
    		System.out.println("Saldo insuficiente para " + cliente );
    	}
    	
    }
    
    public void setSaldo(double saldo){
        
            this.saldo = saldo;
    
    }
    
    public double getSaldo(){
        return saldo;
    }
    
    
    public void setV1(int v1){
        
            this.v1 = v1;
    
    }
    
    public int getV1(){
        return v1;
    }
    
    public void setV2(int v2){
        this.v2 = v2;
    }
    
    public int getV2(){
        return v2;
    }
    
    public void setV3(int v3){
        this.v3 = v1;
    }
    
    public int getV3(){
        return v3;
    }
    
    public void setV4(int v4){
        this.v4 = v4;
    }
    
    public int getV4(){
        return v4;
    }
    
    public void setV5(int v5){
        this.v5 = v5;
    }
    
    public int getV5(){
        return v5;
    }
    
    private void jTxtDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDepositarActionPerformed
            
    }//GEN-LAST:event_jTxtDepositarActionPerformed

    public void jTextName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextName1ActionPerformed
               
    }//GEN-LAST:event_jTextName1ActionPerformed

    public void jTextValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValor1ActionPerformed
        setV1(Integer.parseInt(jTextValor1.getText()));
        System.out.println(getV1());
        
        
    }//GEN-LAST:event_jTextValor1ActionPerformed

    public void jTextName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextName2ActionPerformed

    public void jTextValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValor2ActionPerformed

    public void jTextName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextName3ActionPerformed

    public void jTextValor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValor3ActionPerformed

    public void jTextName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextName4ActionPerformed

    public void jTextValor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValor4ActionPerformed

    public void jTextName5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextName5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextName5ActionPerformed

    public void jTextValor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValor5ActionPerformed

    public void jTxtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSaldoActionPerformed
       
    }//GEN-LAST:event_jTxtSaldoActionPerformed

    private void jPagarAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagarAllActionPerformed
            ComprasEmFamilia irAsCompras = new ComprasEmFamilia();
            //TelaPrincipal tela = new TelaPrincipal();
            
            setSaldo(Integer.valueOf(jTxtSaldo.getText()));
            System.out.println("Saldo Conta "+ getSaldo());
            //System.out.println("Original "+ saldoOriginal);
            
                if(!jTextValor1.getText().trim().equals("")){
                    setV1(Integer.valueOf(jTextValor1.getText()));
                    System.out.println("Valor1 "+getV1());
                }
                
                if(!jTextName1.getText().trim().equals("")){
                    new  Thread((Runnable) irAsCompras, jTextName1.getText()).start();
                }
                
                if(!jTextName2.getText().trim().equals("")){
                    new  Thread((Runnable) irAsCompras, jTextName2.getText()).start();
                }
                if(!jTextName3.getText().trim().equals("")){
                    new  Thread((Runnable) irAsCompras, jTextName3.getText()).start();
                }
                if(!jTextName4.getText().trim().equals("")){
                    new  Thread((Runnable) irAsCompras, jTextName4.getText()).start();
                }
                if(!jTextName5.getText().trim().equals("")){
                    new  Thread((Runnable) irAsCompras, jTextName5.getText()).start();
                }
                
		
    }//GEN-LAST:event_jPagarAllActionPerformed

    private void jPagarAllSincronizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagarAllSincronizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPagarAllSincronizadoActionPerformed

    private void jConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConcluirActionPerformed
       
        if(jTxtDepositar.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Prencha o Campo Depositar");            
        } else{            
              jTxtSaldo.setText((jTxtDepositar.getText()));
        
              saldo = Double.parseDouble(jTxtSaldo.getText());
              setSaldo(saldo);
        }
        
       

    }//GEN-LAST:event_jConcluirActionPerformed

    private void jPagar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagar1ActionPerformed
        
          
        if(jTextName1.getText().trim().equals("") || jTextValor1.getText().trim().equals("") ||  
                jTxtSaldo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Prencha os Campos");
        } else if (Integer.parseInt(jTxtSaldo.getText()) < Integer.parseInt(jTextValor1.getText())){
             JOptionPane.showMessageDialog(null, "VALOR Maior que SALDO");
        }
         
        
        if(!jTextName1.getText().trim().equals("") && !jTextValor1.getText().trim().equals("") &&  
                !jTxtSaldo.getText().trim().equals("") &&
                Integer.parseInt(jTxtSaldo.getText()) >= Integer.parseInt(jTextValor1.getText())) {
             
                   int pagar = Integer.parseInt(jTxtSaldo.getText()) - 
                   Integer.parseInt(jTextValor1.getText());
                   jTxtSaldo.setText(String.valueOf(pagar));
                   status1.setState(true);
                } 
        
    }//GEN-LAST:event_jPagar1ActionPerformed

    private void jPagar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagar2ActionPerformed
            
        if(jTextName2.getText().trim().equals("") || jTextValor2.getText().trim().equals("") ||  
                jTxtSaldo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Prencha os Campos");
        } else if (Integer.parseInt(jTxtSaldo.getText()) < Integer.parseInt(jTextValor2.getText())){
             JOptionPane.showMessageDialog(null, "VALOR Maior que SALDO");
        }

        if(!jTextName2.getText().trim().equals("") && !jTextValor2.getText().trim().equals("") &&  
                !jTxtSaldo.getText().trim().equals("") &&
                Integer.parseInt(jTxtSaldo.getText()) >= Integer.parseInt(jTextValor2.getText())) {
             
                   int pagar = Integer.parseInt(jTxtSaldo.getText()) - 
                   Integer.parseInt(jTextValor2.getText());
                   jTxtSaldo.setText(String.valueOf(pagar));
                   status2.setState(true);
                } 
    }//GEN-LAST:event_jPagar2ActionPerformed

    private void jPagar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagar3ActionPerformed

           if(jTextName3.getText().trim().equals("") || jTextValor3.getText().trim().equals("") ||  
                jTxtSaldo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Prencha os Campos");
        } else if (Integer.parseInt(jTxtSaldo.getText()) < Integer.parseInt(jTextValor3.getText())){
             JOptionPane.showMessageDialog(null, "VALOR Maior que SALDO");
        }

        if(!jTextName3.getText().trim().equals("") && !jTextValor3.getText().trim().equals("") &&  
                !jTxtSaldo.getText().trim().equals("") &&
                Integer.parseInt(jTxtSaldo.getText()) >= Integer.parseInt(jTextValor3.getText())) {
             
                   int pagar = Integer.parseInt(jTxtSaldo.getText()) - 
                   Integer.parseInt(jTextValor3.getText());
                   jTxtSaldo.setText(String.valueOf(pagar));
                   status3.setState(true);
                } 
        
    }//GEN-LAST:event_jPagar3ActionPerformed

    private void jPagar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagar4ActionPerformed

           if(jTextName4.getText().trim().equals("") || jTextValor4.getText().trim().equals("") ||  
                jTxtSaldo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Prencha os Campos");
        } else if (Integer.parseInt(jTxtSaldo.getText()) < Integer.parseInt(jTextValor4.getText())){
             JOptionPane.showMessageDialog(null, "VALOR Maior que SALDO");
        }

        if(!jTextName4.getText().trim().equals("") && !jTextValor4.getText().trim().equals("") &&  
                !jTxtSaldo.getText().trim().equals("") &&
                Integer.parseInt(jTxtSaldo.getText()) >= Integer.parseInt(jTextValor4.getText())) {
             
                   int pagar = Integer.parseInt(jTxtSaldo.getText()) - 
                   Integer.parseInt(jTextValor4.getText());
                   jTxtSaldo.setText(String.valueOf(pagar));
                   status4.setState(true);
                } 
        
    }//GEN-LAST:event_jPagar4ActionPerformed

    private void jPagar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagar5ActionPerformed

           if(jTextName5.getText().trim().equals("") || jTextValor5.getText().trim().equals("") ||  
                jTxtSaldo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Prencha os Campos");
        } else if (Integer.parseInt(jTxtSaldo.getText()) < Integer.parseInt(jTextValor5.getText())){
             JOptionPane.showMessageDialog(null, "VALOR Maior que SALDO");
        }

        if(!jTextName5.getText().trim().equals("") && !jTextValor5.getText().trim().equals("") &&  
                !jTxtSaldo.getText().trim().equals("") &&
                Integer.parseInt(jTxtSaldo.getText()) >= Integer.parseInt(jTextValor5.getText())) {
             
                   int pagar = Integer.parseInt(jTxtSaldo.getText()) - 
                   Integer.parseInt(jTextValor5.getText());
                   jTxtSaldo.setText(String.valueOf(pagar));
                   status5.setState(true);
                } 
        
    }//GEN-LAST:event_jPagar5ActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        
        System.out.println("Saldo " +getSaldo());
       
        if(!jTextValor1.getText().trim().equals("")){
            setV1(Integer.valueOf(jTextValor1.getText()));
            System.out.println("v1 "+getV1());
        }
        if (!jTextValor2.getText().trim().equals("")){
            setV2(Integer.valueOf(jTextValor2.getText()));
             System.out.println("v2 "+getV2());
        }
        if (!jTextValor3.getText().trim().equals("")){
             setV3(Integer.valueOf(jTextValor3.getText()));
             System.out.println("v3 "+getV3());
        }
        if (!jTextValor4.getText().trim().equals("")){
            setV4(Integer.valueOf(jTextValor4.getText()));
            System.out.println("v4 "+getV4());
        }
        if (!jTextValor5.getText().trim().equals("")){
            setV5(Integer.valueOf(jTextValor5.getText()));
            System.out.println("v5 "+getV5());
        }  
        
        
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton jConcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jPagar1;
    private javax.swing.JButton jPagar2;
    private javax.swing.JButton jPagar3;
    private javax.swing.JButton jPagar4;
    private javax.swing.JButton jPagar5;
    public javax.swing.JButton jPagarAll;
    private javax.swing.JButton jPagarAllSincronizado;
    public javax.swing.JTextField jTextName1;
    public javax.swing.JTextField jTextName2;
    private javax.swing.JTextField jTextName3;
    private javax.swing.JTextField jTextName4;
    private javax.swing.JTextField jTextName5;
    public javax.swing.JTextField jTextValor1;
    public javax.swing.JTextField jTextValor2;
    private javax.swing.JTextField jTextValor3;
    private javax.swing.JTextField jTextValor4;
    private javax.swing.JTextField jTextValor5;
    private javax.swing.JTextField jTxtDepositar;
    private javax.swing.JTextField jTxtSaldo;
    private java.awt.Checkbox status1;
    private java.awt.Checkbox status2;
    private java.awt.Checkbox status3;
    private java.awt.Checkbox status4;
    private java.awt.Checkbox status5;
    // End of variables declaration//GEN-END:variables
   
}
